---
title: "deploy_dataset"
author: "Claude Cugerone"
date: "2025-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Gather 2019, 2020, 2023 data
```{r}
# Merge individuals from a deployment into a "combined_wdxx.rds" file
library(dplyr)

combine_deployment <- function(deployment) {
  input_dir <- file.path("oceanographic_data_corrected", deployment)
  output_path <- file.path(input_dir, paste0("combined_", deployment, ".rds"))
  
  # List all RDS files in the folder
  files <- list.files(path = input_dir, pattern = "_data\\.rds$", full.names = TRUE)
  
  # Load, merge, and sort data
  combined_data <- files %>%
    lapply(readRDS) %>%
    bind_rows() %>%
    arrange(seal_id, profile_id, date)
  
  # Save the result
  saveRDS(combined_data, output_path)
  
  message("Saved: ", output_path)
  return(invisible(combined_data))
}

combine_deployment("wd11")
combine_deployment("wd12")
combine_deployment("wd20")

```

# Create the global deployment
```{r}
# Merge all deployments to have all individuals in a single RDS
library(dplyr)

# Folder containing all deployment subfolders
base_dir <- "oceanographic_data_corrected"

# Find all combined_*.rds files in all subfolders
combined_files <- list.files(path = base_dir, pattern = "^combined_.*\\.rds$", 
                             full.names = TRUE, recursive = TRUE)

# Load and merge all files
all_data <- combined_files %>%
  lapply(readRDS) %>%
  bind_rows() %>%
  arrange(SEAL_NAME, profile_id, date)

# Save the final file
saveRDS(all_data, file.path(base_dir, "all_deployment.rds"))

```

# High temperature profiles removal
```{r}
# Remove profiles with excessively high temperature
library(dplyr)

df <- readRDS("/home/cactus/Documents/Oceano/M2/LOCEAN/Weddell_seal_fluo/oceanographic_data_corrected/all_deployment.rds")

threshold <- 4
values_above <- unique(df$temperature[df$temperature > threshold])

df_filtered <- df[df$temperature <= threshold, ]

num_removed <- nrow(df) - nrow(df_filtered)

saveRDS(df_filtered, "/home/cactus/Documents/Oceano/M2/LOCEAN/Weddell_seal_fluo/oceanographic_data_corrected/all_deployment_filtered.rds")


```

