---
title: "00_fluo_test"
output:
  html_document:
    df_print: paged
date: "2025-04-10"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r packages}
library(ncdf4) 
library(raster) 
library(ggplot2)
library(dplyr)
library(lubridate)
library(data.table)
library(oce)
library(terra)
library(tidyterra)
library(cmocean)
library(stringr)

```

## Variables
```{r variables}
MAX_CHLA_DEPTH <- 200       # define depth at which to consider dark signal (CHLA "absolute zero")
SURFACE_NOT_NAN <- 4:10

DDU_loc=NULL
DDU_loc$lat = -66.663253
DDU_loc$lon = 140.002335
DDU_loc=as.data.frame(DDU_loc)

```

```{r}
# ROOT_PROJ <- "/home/cactus/Documents/Oceano/M2/LOCEAN/Weddell_seal_fluo"
# DATA_FOLDER <- "oceanographic_data"
# DEPLOY_FOLDER <- "wd31"
# DATA_PATH <- file.path(ROOT_PROJ, DATA_FOLDER, DEPLOY_FOLDER)
# 
# nc_files <- list.files(DATA_PATH, pattern = "\\.nc$", full.names = TRUE)
# ranges_list <- list()
# 
# for (nc_file in nc_files) {
#   nc_data <- nc_open(nc_file)
#   juld <- ncvar_get(nc_data, "JULD")
#   
#   dateTime <- as.POSIXct(juld * 86400, origin = "1950-01-01", tz = "UTC")
#   dateTime <- round(dateTime, units = "mins")
#   
#   ranges_list[[basename(nc_file)]] <- range(dateTime, na.rm = TRUE)
#   nc_close(nc_data)
# }
# 
# for (file_name in names(ranges_list)) {
#   cat("\nFichier:", file_name, "\n")
#   print(ranges_list[[file_name]])
# }
```

## Paths
```{r paths}
ROOT_PROJ <- "/home/cactus/Documents/Oceano/M2/LOCEAN/Weddell_seal_fluo"

DATA_FOLDER <- "oceanographic_data"
DEPLOY_FOLDER <- "wd11"
SEAL_NAME <- "wd11-687-18"
SEAL_FILE <- paste0(SEAL_NAME, "_hr2_prof.nc")
NC_PATH <- file.path(ROOT_PROJ, DATA_FOLDER, DEPLOY_FOLDER, SEAL_FILE)

BATHY_FOLDER <- "bathy"
FINE_TOPO_FILE <- "gvdem100v3/w001001.adf"
LARGE_TOPO_FILE <- "gebco_2023_n-50.0_s-79.0_w90.0_e180.0.tif"
BATHY_PATH_FINE <- file.path(ROOT_PROJ, BATHY_FOLDER, FINE_TOPO_FILE)
BATHY_PATH_LARGE <- file.path(ROOT_PROJ, BATHY_FOLDER, LARGE_TOPO_FILE)

FAST_ICE_FOLDER <- "fast_ice"
FAST_ICE_FILE <- "mertz_sara_akiko_19.nc"
FAST_ICE_PATH <- file.path(ROOT_PROJ, FAST_ICE_FOLDER, FAST_ICE_FILE)

AMSR_FOLDER <- "amsr2"
AMSR_FOLDER_YEAR <- "2019"
AMSR_FOLDER_PATH <- file.path(ROOT_PROJ,AMSR_FOLDER,AMSR_FOLDER_YEAR)
AMSR_FILE <- "asi-AMSR2-s3125-20190401-v5.4.tif"
AMSR_PATH <- file.path(ROOT_PROJ,AMSR_FOLDER,AMSR_FOLDER_YEAR,AMSR_FILE)
```

## NetCfd code
```{r nc-code}
nc_data <- nc_open(NC_PATH)
# print(nc_data)
lon <- ncvar_get(nc_data, "LONGITUDE")
lat <- ncvar_get(nc_data, "LATITUDE")
chla <- ncvar_get(nc_data, "CHLA")
light <- ncvar_get(nc_data, "LIGHT")
temp <- ncvar_get(nc_data, "TEMP_ADJUSTED")
psal <- ncvar_get(nc_data,"PSAL_ADJUSTED")
pres <- ncvar_get(nc_data, "PRES_ADJUSTED")
juld <- ncvar_get(nc_data, "JULD")
```

## Long Lat Light
```{r dataframe}
max_depth_dataset <- 150
m = 1:max_depth_dataset
n = 5

dateTime <- as.POSIXct(juld * 86400, origin = "1950-01-01", tz = "UTC")
dateTime <- round(dateTime, units = "mins")  # arrondi à la minute la plus proche
```

```{r corrected lon lat}
diag <- read.csv("diag_2017-2024_forclaude_07apr24.csv", stringsAsFactors = FALSE)
diag$date <- as.POSIXct(diag$date, format="%Y-%m-%d %H:%M")

# extraire l'individu qui nous intéresse et trier par date
df_wd11 <- diag %>% filter(id == SEAL_NAME)
df_wd11 <- df_wd11 %>% arrange(date)

t1 <- as.numeric(df_wd11$date )
t2 <- as.numeric(as.POSIXct(dateTime))

cols <- c("lat", "lon")
interp_results <- lapply(cols, function(col) {
  approx(x = t1, y = df_wd11[[col]], xout = t2, rule = 2)$y
})

names(interp_results) <- paste0(cols, "_corr")
df_interp <- as.data.frame(interp_results)

df_original <- data.frame(lon = lon, lat = lat)

ggplot() +
  geom_point(data = df_original, 
             aes(x = lon, y = lat, color = "Original"), 
             alpha = 0.4, size = 2) +
  geom_point(data = df_interp, 
             aes(x = lon_corr, y = lat_corr, color = "Interpolated"), 
             alpha = 0.4, size = 2) +
  scale_color_manual(
    name = "Type de données",
    values = c("Original" = "blue", "Interpolated" = "red")
  ) +
  labs(
    title = paste0(SURFACE_NOT_NAN[1], " to ", SURFACE_NOT_NAN[length(SURFACE_NOT_NAN)], 
      " m deep"
    ),
    x = "Longitude",
    y = "Latitude"
  ) +
  theme_minimal()
```

```{r}
lon <- df_interp$lon_corr
lat <- df_interp$lat_corr
```

```{r NaColumns}
col_na_only <- apply(light, 2, function(col) all(is.na(col)))
which(col_na_only)

cat("Number of only N/A columns :", sum(col_na_only), "\n\n")
```

```{r NaColumns}
light_subset <- light[1:MAX_CHLA_DEPTH, !col_na_only] # sesf031_light_data_preprocess1_nonNan2 : erasing NaN profiles
lat_subset <- lat[!col_na_only]
lon_subset <- lon[!col_na_only]
date_subset <- dateTime[!col_na_only]

chla_subset <- chla [1:MAX_CHLA_DEPTH, !col_na_only]
temp_subset <- temp [1:MAX_CHLA_DEPTH, !col_na_only]
psal_subset <- psal [1:MAX_CHLA_DEPTH, !col_na_only]
pres_subset <- pres [1:MAX_CHLA_DEPTH, !col_na_only]

total_light <- colSums(light_subset, na.rm = TRUE)
profil_names <- as.character(seq_along(total_light))

plot(
  total_light,
  type = "b",                     
  pch = 18,                        
  col = "blue",
  xlab = "Profil n°",
  ylab = "Total lumière (µmol/m²/s)",
  main = paste0("Lumière totale par profile : ", SEAL_NAME),
  xaxt = "n"                       
)

axis(1, at = seq(1, length(profil_names), by = 20), labels = profil_names[seq(1, length(profil_names), by = 20)])
```

```{r DarkValue}

last_nonzero_vals <- sapply(1:ncol(light_subset), function(n) {
  idx <- which(!is.na(light_subset[, n]) & light_subset[, n] != 0)
  if (length(idx) > 0) {
    light_subset[max(idx), n]
  }
})

light_corrected <- sweep(light_subset, 2, last_nonzero_vals, FUN = "-") # dark-value ? Not sure mhmhmhm

# Plot only one of the 150
plot(light_subset[1:MAX_CHLA_DEPTH, n], pres[1:MAX_CHLA_DEPTH, n], type = "l", col = "blue",
     ylim = rev(range(pres[1:200, n], na.rm = TRUE)),
     xlim = c(-10,15),
     xlab = "Light", ylab = "Depth", main = paste("Profil", n, "- Dark value: ", last_nonzero_vals[n]))

lines(light_corrected[1:MAX_CHLA_DEPTH, n], pres[1:MAX_CHLA_DEPTH, n], col = "red")

legend("bottomright", legend = c("Original", "Corrected"),
       col = c("blue", "red"), lty = 1, bty = "n")
```

```{r}
matplot(light[1:MAX_CHLA_DEPTH,], pres[1:MAX_CHLA_DEPTH,],
        type = "l",
        ylim = rev(c(0, MAX_CHLA_DEPTH)),
        lty = 1,
        xlab = "Light (µmol/m²/s)",
        ylab = "Depth (m)",
        main = paste0("Light profiles : ", SEAL_NAME))
grid()

matplot(light_corrected, pres[1:MAX_CHLA_DEPTH,],
        type = "l",
        ylim = rev(c(0, MAX_CHLA_DEPTH)),
        lty = 1,
        xlab = "Light (µmol/m²/s)",
        ylab = "Depth (m)",
        main = paste0("Light profiles corrected : ", SEAL_NAME))
grid()

light <- light_corrected
```
```{r SaveAndClassifyLightProfiles, echo=FALSE}

dir_standard = "profils_light_standard"
dir_atypique = "profils_light_atypique"
dir.create(dir_standard, showWarnings = FALSE)
dir.create(dir_atypique, showWarnings = FALSE)

nlight = ncol(light)

for (i in 1:nlight) {
  profil_light <- light[, i]
  profil_pres <- pres_subset[, i]
  
  delta_light <- profil_light - profil_light[1]

  if (any(delta_light > 0, na.rm = TRUE)) {
    class_dir <- dir_atypique
  } else {
    class_dir <- dir_standard
  }
  
  filename <- paste0(class_dir, "/profil_light", i, ".png")
  
  png(filename, width = 800, height = 600)
  
  plot(profil_light, profil_pres,
       type = "l",
       xlim = c(-10,10),
       ylim = rev(c(0, MAX_CHLA_DEPTH)),
       xlab = "Light (µmol/m²/s)",
       ylab = "Press",
       main = paste0("Profil light - Col ", i," (", format(date_subset[i], "%Y-%m-%d"), ")"))
  grid()
  
  dev.off()
}

cat("Classification terminée :\n")
cat(nlight, "profils analysés\n")
cat("->", length(list.files(dir_standard)), "profils standards dans", dir_standard, "\n")
cat("->", length(list.files(dir_atypique)), "profils atypiques dans", dir_atypique, "\n\n")

```

```{r PlotOneProfile}
# Layout pour 3 graphiques côte à côte
par(mfrow = c(1, 4))

n = 96

# Plot 1: Lumière
plot(light[m,n], pres[m,n],
     type = "l",
     xlim = range(light[,n], na.rm = TRUE),
     ylim = rev(c(0, max_depth_dataset)),
     xlab = "Light (µmol/m²/s)",
     ylab = "Depth (m)")
grid()

# Plot 2: Température
plot(temp[m,n], pres[m,n],
     type = "l",
     xlab = "Temperature (°C)",
     xlim = range(temp[,n], na.rm = TRUE),
     ylim = rev(c(0, max_depth_dataset)),
     ylab = "")
grid()

# Plot 3: Salinité
plot(psal[m,n], pres[m,n],
     type = "l",
     xlab = "Salinity",
     xlim = range(psal[,n], na.rm = TRUE),
     ylim = rev(c(0, max_depth_dataset)),
     ylab = "")
grid()

# Plot 4: Chla
plot(chla[m,n], pres[m,n],
     type = "l",
     xlab = "CHLA (fluo)",
     xlim = c(-10, 10),
     ylim = rev(c(0, max_depth_dataset)),
     ylab = "")
grid()

mtext(paste0(SEAL_NAME, " : ", n, "/", ncol(light), " (", format(date_subset[n], "%Y-%m-%d"), ")"), side = 3, line = -2, outer = TRUE)

```

```{r dataframe}

depth_interval <- pres[SURFACE_NOT_NAN,1]
light_interval <- light[SURFACE_NOT_NAN, ]

depth_diff <- c(diff(depth_interval), 0)  

light_surf_avg <- apply(light_interval, 2, function(x) {
  sum(x * depth_diff, na.rm = TRUE) / sum(depth_diff, na.rm = TRUE)
})

light_20m <- light[20, ]
light_40m <- light[40, ]

df_light <- data.frame(
  lon = lon_subset,
  lat = lat_subset,
  date = date_subset,
  light_surf = light_surf_avg,
  light_20 = light_20m,
  light_40 = light_40m
)

df_10m_clean <- df_light %>% filter(!is.na(light_surf))
df_20m_clean <- df_light %>% filter(!is.na(light_20))
df_40m_clean <- df_light %>% filter(!is.na(light_40))

n_profiles_surf <- length(df_10m_clean$light_surf)
n_profiles_20 <- length(df_20m_clean$light_20)
n_profiles_40 <- length(df_40m_clean$light_40)

ggplot(df_10m_clean, aes(x = lon, y = lat, color = light_surf)) +
  geom_point(size = 2) +
  scale_color_viridis_c(limits = c(0, 10), oob = scales::squish) +
  labs(
    title = paste0(n_profiles_surf," light profiles (", SURFACE_NOT_NAN[1], " to ",SURFACE_NOT_NAN[7],"m deep)"),
    x = "Longitude",
    y = "Latitude",
    color = "Light\nln(µmol/m²/s)"
  ) +
  theme_minimal()

ggplot(df_20m_clean, aes(x = lon, y = lat, color = light_20)) +
  geom_point(size = 2) +
  scale_color_viridis_c(limits = c(0, 10), oob = scales::squish) +
  labs(
    title = paste0(n_profiles_20," light profiles (", 20,"m deep)"),
    x = "Longitude",
    y = "Latitude",
    color = "Light\nln(µmol/m²/s)"
  ) +
  theme_minimal()

ggplot(df_40m_clean %>% filter(!is.na(light_40)), aes(x = lon, y = lat, color = light_40)) +
  geom_point(size = 2) +
  scale_color_viridis_c(limits = c(0, 10), oob = scales::squish) +
  labs(
    title = paste0(n_profiles_40, " light profiles (", 40, "m deep)"),
    x = "Longitude",
    y = "Latitude",
    color = "Light\nln(µmol/m²/s)"
  ) +
  theme_minimal()

```
```{r}
solar_angle = sunAngle(date_subset, lon_subset, lat_subset)$altitude
solar_threshold <- -12

# tranche de 0.1 : 10 - 0.5 : 2 - 0.05 : 20
lat_bin <- floor(lat_subset * 20) / 20

df_solar <- data.frame(
  date = date_subset,
  lat = lat_subset,
  lat_bin = lat_bin,
  lon = lon_subset,
  solar_angle = solar_angle,
  light = light_surf_avg
)

df_solar <- df_solar %>%
  mutate(period = case_when(
    solar_angle >= 0 ~ "Day",
    solar_angle < 0 & solar_angle > solar_threshold ~ "Twilight",
    solar_angle <= solar_threshold ~ "Night"
  ))

nPeriod_by_lat <- df_solar %>%
  group_by(lat_bin, period) %>%
  summarise(n = n(), .groups = "drop")

ggplot(df_solar, aes(x = date, y = solar_angle, color = period)) +
  geom_point() +
  facet_wrap(~lat_bin, scales = "fixed") +
  coord_cartesian(ylim = c(-40, 40)) +
  labs(title = "Solar Angle by Latitude Bin",x = "Date",y = "Solar Angle (°)") +
  scale_color_manual(values = c("Day" = "red", "Twilight" = "green", "Night" = "navy")) +
  theme_minimal()


ggplot(df_solar, aes(x = date, y = light, color = period)) +
  geom_point() +
  facet_wrap(~lat_bin, scales = "free_y") +
  coord_cartesian(ylim = c(-5, 15)) +
  labs(title = paste0("Light (", SURFACE_NOT_NAN[1], " to ",SURFACE_NOT_NAN[7], "m deep) by Latitude Bin"), x = "Date", y = "ln(µmol/m²/sec)") +
  scale_color_manual(values = c("Day" = "red", "Twilight" = "green", "Night" = "navy")) +
  theme_minimal()


```

```{r LightThroughTime}

nPeriod = df_solar %>%  count(period)

cat("Number of Day values :", nPeriod$n[1], "\n")
cat("Number of Night values :", nPeriod$n[2], "\n")
cat("Number of Twilight values :", nPeriod$n[3], "\n")

ggplot(df_solar, aes(x = date, y = solar_angle, color = period)) +
  geom_point() +
  labs(title = "Solar Angle",
       x = "Date", y = "Solar Angle (°)") +
  scale_color_manual(values = c("Day" = "red", "Twilight" = "green", "Night" = "navy")) +
  theme_minimal()

vline_dates <- as.POSIXct(c("2019-02-20 01:12:00", "2019-03-21 00:46:00", "2019-04-19 07:30:00"))

ggplot(df_solar, aes(x = date, y = light, color = period)) +
  geom_point() +
  geom_vline(xintercept = vline_dates, linetype = "dashed", color = "black") +
  annotate("text", x = vline_dates[1], y = max(df_solar$light, na.rm = TRUE), label = "20/02\n🌙", angle = 90, vjust = -0.5, size = 3) +
  annotate("text", x = vline_dates[2], y = max(df_solar$light, na.rm = TRUE), label = "21/03\n🌙", angle = 90, vjust = -0.5, size = 3) +
  annotate("text", x = vline_dates[3], y = max(df_solar$light, na.rm = TRUE), label = "19/04\n🌙", angle = 90, vjust = -0.5, size = 3) +
  labs(
    title = paste0("Light (", SURFACE_NOT_NAN[1], " to ", SURFACE_NOT_NAN[7], "m deep)"),
    x = "Date", y = "ln(µmol/m²/sec)"
  ) +
  scale_color_manual(values = c("Day" = "red", "Twilight" = "green", "Night" = "navy")) +
  theme_minimal()
```
```{r}
df_solar$lon <- lon_subset
df_solar$lat <- lat_subset

lon_center <-  DDU_loc$lon 
lat_center <-  DDU_loc$lat

df_solar <- df_solar %>%
  mutate(zone = case_when(
    lon <= lon_center & lat >= lat_center ~ "Nord-Ouest",
    lon > lon_center & lat >= lat_center ~ "Nord-Est",
    lon <= lon_center & lat < lat_center ~ "Sud-Ouest",
    lon > lon_center & lat < lat_center ~ "Sud-Est"
  ))

ggplot(df_solar, aes(x = lon, y = lat, color = zone, shape = period)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_point(aes(x = DDU_loc$lon, y = DDU_loc$lat), color = "red", shape = 4, size = 3, stroke = 1) +  # croix rouge
  annotate("text", x = DDU_loc$lon, y = DDU_loc$lat, label = "DDU", hjust = -0.2, vjust = -0.5, color = "red", size = 4) +  # étiquette
  labs(title = "Zones (couleur) et période jour/nuit/crépuscule (forme)", x = "Longitude", y = "Latitude") +
  scale_color_manual(values = c("Nord-Ouest" = "darkorange", "Nord-Est" = "purple", "Sud-Ouest" = "blue", "Sud-Est" = "darkgreen")) +
  scale_shape_manual(values = c("Day" = 16, "Twilight" = 17, "Night" = 15)) +
  theme_minimal()

```

```{r}
df_solar <- df_solar %>%
  mutate(distance_to_center = sqrt((lon - lon_center)^2 + (lat - lat_center)^2))

df_solar <- df_solar %>%
  mutate(distance_group = case_when(
    distance_to_center < 0.05 ~ "Centre",
    distance_to_center < 0.15 ~ "Périphérie proche",
    TRUE ~ "Périphérie lointaine"
  ))

ggplot(df_solar, aes(x = lon, y = lat, color = distance_group, shape = period)) +
  geom_point(size = 2, alpha = 0.8) +
  geom_point(aes(x = DDU_loc$lon, y = DDU_loc$lat), color = "red", shape = 4, size = 3, stroke = 1) +  # croix rouge
  annotate("text", x = DDU_loc$lon, y = DDU_loc$lat, label = "DDU", hjust = -0.2, vjust = -0.5, color = "red", size = 4) +  # étiquette
  labs(title = "", x = "Longitude", y = "Latitude") + scale_color_manual(values = c("Centre" = "firebrick", "Périphérie proche" = "goldenrod", "Périphérie lointaine" = "steelblue")) +
  scale_shape_manual(values = c("Day" = 16, "Twilight" = 17, "Night" = 15)) +
  theme_minimal()

```

```{r extract Suspicious solar profiles}
# CODE POUR LA PLUS FORTE VALEUR DANS LA NUIT
# max_night_light <- df_solar %>%
#   filter(period == "Night") %>%
#   summarise(max_light = max(light, na.rm = TRUE)) %>%
#   pull(max_light)
# 
# night_rows <- which(df_solar$period == "Night")
# local_max_index <- which.max(df_solar$light[night_rows])
# global_max_index <- night_rows[local_max_index]

global_max_index <- 99

plot(light[m,global_max_index], pres[m,global_max_index],
     type = "l",
     xlim = range(light[,global_max_index], na.rm = TRUE),
     ylim = rev(c(0, 50)),
     xlab = "Light ln(µmol/m²/s)",
     ylab = "Depth (m)",
     main = paste0("profil index: ", global_max_index, " - Value: ",  sprintf("%.2f", max_night_light), " (", format(date_subset[global_max_index], "%Y-%m-%d"), ")"))
grid()

```

## Light and ice
```{r}
LON_MIN <- 130
LON_MAX <- 150
LAT_MIN <- -68
LAT_MAX <- -65
```

```{r}
fine_topo <- raster(BATHY_PATH_FINE)
fine_topo[fine_topo >=0] <-NA
fine_topo_spat <- terra::rast(fine_topo)

large_topo <- raster(BATHY_PATH_LARGE)
large_topo[large_topo >=0] <-NA
large_topo_spat <- terra::rast(large_topo)

fine_topo_spat <- crop(fine_topo_spat, extent(LON_MIN, LON_MAX, LAT_MIN, LAT_MAX))
large_topo_spat <- crop(large_topo_spat, extent(LON_MIN, LON_MAX, LAT_MIN, LAT_MAX))
```

```{r}
prj <- "+proj=stere +lat_0=-90 +lat_ts=-70 +datum=WGS84"
ex <- c(-2691055, 2933945, -2390156, 2309844)

fast_ice_raster <- rast(FAST_ICE_PATH, "Fast_Ice_Time_Series")
set.ext(fast_ice_raster, ext(ex))
set.crs(fast_ice_raster, crs(prj))
#plot(fast_ice_raster[[1]], legend = FALSE) # le continent

points <- cbind(
  lon = c(LON_MIN, LON_MAX),  
  lat = c(LAT_MIN, LAT_MAX)
)

prjpoints <- project(points, to = prj, from = "EPSG:4326")
new_ex<-extent(prjpoints[2,1],prjpoints[1,1],prjpoints[2,2],prjpoints[1,2])
new_r=crop(fast_ice_raster,new_ex)
# From feb to may
time_index <- seq(1,4, by = 1) 
x_sub <- subset(new_r, time_index)
plot(x_sub, legend = FALSE)
```

```{r}
x_sub2= project(x_sub, crs(large_topo_spat), 
                res = res(large_topo_spat)) 

# Create a sequence of months between the first and last month
start <- format(as.Date("2019-02-05"), "%m")
end <- format(as.Date("2019-05-06"), "%m")

months_seq <- seq(from = start, to = end)

# Extract the month names from the sequence
month_names <- paste0("2019 - ", month.name[months_seq])

names(x_sub2) <- month_names
plot(x_sub2, legend = FALSE)
x_sub2 <- crop(x_sub2, extent(LON_MIN, LON_MAX, LAT_MIN, LAT_MAX))
plot(x_sub2, legend = FALSE)

x_sub2=round(x_sub2)
#description: Classified surface type: 0 = pack ice or ocean; 1 = continent; 2 = islands; 3 = ice shelf; 4 = fast ice; 5 = manual fast ice edge; 6 = auto fast ice edge.
x_sub2[x_sub2 == 0 |x_sub2 == 1 | x_sub2 == 2 | x_sub2 == 3 | x_sub2 == 5| x_sub2 == 6] <- NA

glacier=x_sub2[[4]]
```

```{r}
# TRAITER LES RASTERS ENTIERS : TROP LONG. LE CODE SUIVANT TRAITE SEULEMENT LA PARTIE CROPPE : PLUS RAPIDE

# library(stringr)
# 
# wgs <- "+proj=longlat +ellps=WGS84"
# amsr_dir <- AMSR_FOLDER_PATH
# all_files <- list.files(amsr_dir, full.names = TRUE)
# 
# target_year_month <- "201901"
# 
# selected_files <- all_files[
#   str_detect(all_files, paste0("s3125-", target_year_month))
# ]
# 
# raster_list <- lapply(selected_files, function(f) {
#   r <- raster(f)
#   r[r > 100] <- NA_real_
#   r
# })
# 
# raster_stack <- stack(raster_list)
# mean_raster <- calc(raster_stack, fun = mean, na.rm = TRUE)
# median_raster <- calc(raster_stack, fun = median, na.rm = TRUE)
# sd_raster <- calc(raster_stack, fun = sd, na.rm = TRUE)
# 
# points <- cbind(
#   lon = c(LON_MIN, LON_MAX),  
#   lat = c(LAT_MIN, LAT_MAX)
# )
# 
# boxext <- extent(projectExtent(raster(extent(c(LON_MIN, LON_MAX, LAT_MIN, LAT_MAX)), crs = wgs), projection(mean_raster)))
# 
# mean_raster_cropped <- crop(mean_raster, boxext)
# median_raster_cropped <- crop(median_raster, boxext)
# sd_raster_cropped <- crop(sd_raster, boxext)
# 
# mean_raster_cropped_wgs <- projectRaster(mean_raster_cropped, crs = wgs)
# median_raster_cropped_wgs <- projectRaster(median_raster_cropped, crs = wgs)
# sd_raster_cropped_wgs <- projectRaster(sd_raster_cropped, crs = wgs)
# 
# mean_spat <- rast(mean_raster_cropped_wgs)
# median_spat <- rast(median_raster_cropped_wgs)
# sd_spat <- rast(sd_raster_cropped_wgs)
# 
# plot(mean_spat, main = "Moyenne AMSR - Janvier 2019")
# plot(median_spat, main = "Médiane AMSR - Janvier 2019")
# plot(sd_spat, main = "Écart-type AMSR - Janvier 2019")
# 
```

```{r}

wgs <- "+proj=longlat +ellps=WGS84"
amsr_dir <- AMSR_FOLDER_PATH
all_files <- list.files(amsr_dir, full.names = TRUE)

target_year_month <- "201901"
date_obj <- as.Date(paste0(target_year_month, "01"), format = "%Y%m%d")
formatted_title <- format(date_obj, "%B %Y") 

selected_files <- all_files[str_detect(all_files, paste0("s3125-", target_year_month))]

raster_list <- lapply(selected_files, function(f) {
  r <- raster(f)
  r[r > 100] <- NA_real_
  r
})

raster_stack <- stack(raster_list)

points <- cbind(lon = c(LON_MIN, LON_MAX), lat = c(LAT_MIN, LAT_MAX))
boxext <- extent(projectExtent(raster(extent(c(LON_MIN, LON_MAX, LAT_MIN, LAT_MAX)), crs = wgs), projection(mean_raster)))
raster_cropped <- crop(raster_stack, boxext)

mean_raster <- calc(raster_cropped, fun = mean, na.rm = TRUE)
median_raster <- calc(raster_cropped, fun = median, na.rm = TRUE)
sd_raster <- calc(raster_cropped, fun = sd, na.rm = TRUE)

mean_raster_wgs <- projectRaster(mean_raster, crs = wgs)
median_raster_wgs <- projectRaster(median_raster, crs = wgs)
sd_raster_wgs <- projectRaster(sd_raster, crs = wgs)

mean_spat <- rast(mean_raster_wgs)
median_spat <- rast(median_raster_wgs)
sd_spat <- rast(sd_raster_wgs)

plot(mean_spat, main = paste("AMSR mean -", formatted_title))
plot(median_spat, main = paste("AMSR mediane -", formatted_title))
plot(sd_spat, main = paste("AMSR  SD -", formatted_title))
```

```{r Draft map SIC FI}
month_profile = 4
profiles_per_month <- df_surface_clean %>% filter(lubridate::month(date) == month_profile)

ggplot() +
  geom_spatraster_contour(data = fine_topo_spat, alpha = 0.6)+ #bathy
  geom_spatraster_contour_text(data = fine_topo_spat, alpha = 0.6)+
  geom_spatraster(data = mean_spat, alpha = 0.6)+ # moyenne AMSR2 sur le mois 
  geom_spatraster(data = glacier, alpha = 0.6)+ # glace
  geom_point(data = profiles_per_month, aes(x = lon, y = lat), shape = 21, color = "black", fill = "yellow", size = 1) +  
  xlab("Longitude") + ylab("Latitude")+
  theme_minimal()
```

```{r}
ggplot() +
  geom_spatraster_contour(data = fine_topo_spat, alpha = 0.6) + # bathy
  geom_spatraster_contour_text(data = fine_topo_spat, alpha = 0.6) +
  geom_spatraster(data = mean_spat, alpha = 0.6) + # moyenne AMSR2 sur le mois
  geom_spatraster(data = glacier, alpha = 0.6) + # glacier
  geom_point(data = profiles_per_month, aes(x = lon, y = lat), shape = 21, color = "black", fill = "yellow", size = 1) +
  xlab("Longitude") + ylab("Latitude") +
  theme_minimal() +
  coord_sf(xlim = c(139, 141),ylim = c(-66.8, -66))
```

```{r}
library(sf)
dt_ddu <- format(profiles_per_month, tz = "Australia/Hobart", usetz = TRUE)
profiles_per_month$month <- lubridate::month(profiles_per_month$date)

points_sf <- st_as_sf(profiles_per_month, coords = c("lon", "lat"), crs = 4326) # Transforme en objets spatiaux
points_vect <- terra::vect(points_sf)

glacier_mask <- glacier
glacier_mask[glacier_mask == 4] <- 1

extract_mean   <- terra::extract(mean_spat, points_vect, ID = FALSE)
extract_median <- terra::extract(median_spat, points_vect, ID = FALSE)
extract_sd     <- terra::extract(sd_spat, points_vect, ID = FALSE)
extract_glac   <- terra::extract(glacier_mask, points_vect, ID = FALSE)

profiles_per_month$SICm_mean   <- extract_mean[,1]
profiles_per_month$SICm_median <- extract_median[,1]
profiles_per_month$SICm_sd     <- extract_sd[,1]
profiles_per_month$glacier_presence <- extract_glac[,1]

```

```{r SaveAndClassifyChlaProfiles}

dir_standard = "profils_chla_standard"
dir_atypique = "profils_chla_atypique"
dir.create(dir_standard, showWarnings = FALSE)
dir.create(dir_atypique, showWarnings = FALSE)

nchla = ncol(chla)

for (i in 1:nchla) {
  profil_chla <- chla[, i]
  profil_pres <- pres[, i]
  
  delta_chla <- profil_chla - profil_chla[1]

  if (any(delta_chla > 0, na.rm = TRUE)) {
    class_dir <- dir_atypique
  } else {
    class_dir <- dir_standard
  }
  
  filename <- paste0(class_dir, "/profil_chla", i, ".png")
  
  png(filename, width = 800, height = 600)
  
  plot(profil_chla, profil_pres,
       type = "l",
       xlim = c(-10,10),
       ylim = rev(c(0, MAX_CHLA_DEPTH)),
       xlab = "chla (mg/m³)",
       ylab = "Press",
       main = paste("Profil chla - Col", i))
  grid()
  
  dev.off()
}

cat("Classification terminée :\n")
cat(nchla, "profils analysés\n")
cat("->", length(list.files(dir_standard)), "profils standards dans", dir_standard, "\n")
cat("->", length(list.files(dir_atypique)), "profils atypiques dans", dir_atypique, "\n\n")

```

