---
title: "Plot_QDs_MLDs"
author: "Claude Cugerone"
date: "2025-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(ggplot2)
library(dplyr)

# Déploiements à inclure
deployments <- c("wd11", "wd12", "wd20") #wd31 comming soon

# Lire et marquer les données
data_list <- lapply(deployments, function(dep) {
  df <- readRDS(paste0("oceanographic_data_corrected/", dep, "/combined_", dep, ".rds"))
  df$deployment <- dep  # ajouter colonne "deployment"
  return(df)
})

# Combiner et nettoyer
data <- bind_rows(data_list) %>%
  filter(!is.na(MLD), !is.na(QD)) %>%
  arrange(deployment, SEAL_NAME, profile_id, date)

data$date <- as.Date(data$date)

# Graphique avec facettes
ggplot(data, aes(x = date, y = MLD, color = SEAL_NAME)) +
  geom_point(shape = 4) +
  geom_smooth(method = "loess", formula = "y ~ x", linewidth = 0.25, se = FALSE) +
  scale_y_reverse() +
  scale_x_date(date_labels = "%b %Y") +
  facet_wrap(~ deployment, scales = "free_x") + 
  labs(x = "", y = "Depth (m)", title = "Mixed Laye Depth by seal and deployment") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Graphique avec facettes
ggplot(data, aes(x = date, y = QD, color = SEAL_NAME)) +
  geom_point(shape = 4) +
  geom_smooth(method = "loess", formula = "y ~ x", linewidth = 0.25, se = FALSE) +
  scale_y_reverse() +
  scale_x_date(date_labels = "%b %Y") +
  facet_wrap(~ deployment, scales = "free_x") + 
  labs(x = "", y = "Depth (m)", title = "Quenching depth by seal and deployment") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

